//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDECINEWeb.PeliculaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeliculaServiceReference.IPeliculaService")]
    public interface IPeliculaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeliculaService/listar", ReplyAction="http://tempuri.org/IPeliculaService/listarResponse")]
        FIDECINEService.Dominio.PeliculaBE[] listar(string str_pNombre, string str_pEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeliculaServiceChannel : FIDECINEWeb.PeliculaServiceReference.IPeliculaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeliculaServiceClient : System.ServiceModel.ClientBase<FIDECINEWeb.PeliculaServiceReference.IPeliculaService>, FIDECINEWeb.PeliculaServiceReference.IPeliculaService {
        
        public PeliculaServiceClient() {
        }
        
        public PeliculaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeliculaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FIDECINEService.Dominio.PeliculaBE[] listar(string str_pNombre, string str_pEstado) {
            return base.Channel.listar(str_pNombre, str_pEstado);
        }
    }
}
