//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Pelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Pelicula), "Cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Cartelera), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Cartelera_Sala", "Sala", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Sala), "Cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Cartelera), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Pelicula_CategoriaPelicula", "CategoriaPelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.CategoriaPelicula), "Pelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Pelicula), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_PuntajeAcumulado_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Cliente), "PuntajeAcumulado", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.PuntajeAcumulado), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_TarjetaCliente_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Cliente), "TarjetaCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.TarjetaCliente), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_VisitaCliente_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.Cliente), "VisitaCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.VisitaCliente), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Pelicula_GeneroPelicula", "GeneroPelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.GeneroPelicula), "Pelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Pelicula), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Pelicula_TipoPelicula", "TipoPelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FIDECINEService.TipoPelicula), "Pelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Pelicula), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Promocion_Producto", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Producto), "Promocion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Promocion), true)]

#endregion

namespace FIDECINEService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FideCineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FideCineEntities object using the connection string found in the 'FideCineEntities' section of the application configuration file.
        /// </summary>
        public FideCineEntities() : base("name=FideCineEntities", "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FideCineEntities object.
        /// </summary>
        public FideCineEntities(string connectionString) : base(connectionString, "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FideCineEntities object.
        /// </summary>
        public FideCineEntities(EntityConnection connection) : base(connection, "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cartelera> Cartelera
        {
            get
            {
                if ((_Cartelera == null))
                {
                    _Cartelera = base.CreateObjectSet<Cartelera>("Cartelera");
                }
                return _Cartelera;
            }
        }
        private ObjectSet<Cartelera> _Cartelera;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoriaPelicula> CategoriaPelicula
        {
            get
            {
                if ((_CategoriaPelicula == null))
                {
                    _CategoriaPelicula = base.CreateObjectSet<CategoriaPelicula>("CategoriaPelicula");
                }
                return _CategoriaPelicula;
            }
        }
        private ObjectSet<CategoriaPelicula> _CategoriaPelicula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeneroPelicula> GeneroPelicula
        {
            get
            {
                if ((_GeneroPelicula == null))
                {
                    _GeneroPelicula = base.CreateObjectSet<GeneroPelicula>("GeneroPelicula");
                }
                return _GeneroPelicula;
            }
        }
        private ObjectSet<GeneroPelicula> _GeneroPelicula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pelicula> Pelicula
        {
            get
            {
                if ((_Pelicula == null))
                {
                    _Pelicula = base.CreateObjectSet<Pelicula>("Pelicula");
                }
                return _Pelicula;
            }
        }
        private ObjectSet<Pelicula> _Pelicula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Producto> Producto
        {
            get
            {
                if ((_Producto == null))
                {
                    _Producto = base.CreateObjectSet<Producto>("Producto");
                }
                return _Producto;
            }
        }
        private ObjectSet<Producto> _Producto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Promocion> Promocion
        {
            get
            {
                if ((_Promocion == null))
                {
                    _Promocion = base.CreateObjectSet<Promocion>("Promocion");
                }
                return _Promocion;
            }
        }
        private ObjectSet<Promocion> _Promocion;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PuntajeAcumulado> PuntajeAcumulado
        {
            get
            {
                if ((_PuntajeAcumulado == null))
                {
                    _PuntajeAcumulado = base.CreateObjectSet<PuntajeAcumulado>("PuntajeAcumulado");
                }
                return _PuntajeAcumulado;
            }
        }
        private ObjectSet<PuntajeAcumulado> _PuntajeAcumulado;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sala> Sala
        {
            get
            {
                if ((_Sala == null))
                {
                    _Sala = base.CreateObjectSet<Sala>("Sala");
                }
                return _Sala;
            }
        }
        private ObjectSet<Sala> _Sala;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TarjetaCliente> TarjetaCliente
        {
            get
            {
                if ((_TarjetaCliente == null))
                {
                    _TarjetaCliente = base.CreateObjectSet<TarjetaCliente>("TarjetaCliente");
                }
                return _TarjetaCliente;
            }
        }
        private ObjectSet<TarjetaCliente> _TarjetaCliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoPelicula> TipoPelicula
        {
            get
            {
                if ((_TipoPelicula == null))
                {
                    _TipoPelicula = base.CreateObjectSet<TipoPelicula>("TipoPelicula");
                }
                return _TipoPelicula;
            }
        }
        private ObjectSet<TipoPelicula> _TipoPelicula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VisitaCliente> VisitaCliente
        {
            get
            {
                if ((_VisitaCliente == null))
                {
                    _VisitaCliente = base.CreateObjectSet<VisitaCliente>("VisitaCliente");
                }
                return _VisitaCliente;
            }
        }
        private ObjectSet<VisitaCliente> _VisitaCliente;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cartelera EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCartelera(Cartelera cartelera)
        {
            base.AddObject("Cartelera", cartelera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoriaPelicula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoriaPelicula(CategoriaPelicula categoriaPelicula)
        {
            base.AddObject("CategoriaPelicula", categoriaPelicula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeneroPelicula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeneroPelicula(GeneroPelicula generoPelicula)
        {
            base.AddObject("GeneroPelicula", generoPelicula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pelicula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPelicula(Pelicula pelicula)
        {
            base.AddObject("Pelicula", pelicula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Producto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducto(Producto producto)
        {
            base.AddObject("Producto", producto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Promocion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPromocion(Promocion promocion)
        {
            base.AddObject("Promocion", promocion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PuntajeAcumulado EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPuntajeAcumulado(PuntajeAcumulado puntajeAcumulado)
        {
            base.AddObject("PuntajeAcumulado", puntajeAcumulado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sala EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSala(Sala sala)
        {
            base.AddObject("Sala", sala);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TarjetaCliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarjetaCliente(TarjetaCliente tarjetaCliente)
        {
            base.AddObject("TarjetaCliente", tarjetaCliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoPelicula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoPelicula(TipoPelicula tipoPelicula)
        {
            base.AddObject("TipoPelicula", tipoPelicula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VisitaCliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitaCliente(VisitaCliente visitaCliente)
        {
            base.AddObject("VisitaCliente", visitaCliente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Cartelera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cartelera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cartelera object.
        /// </summary>
        /// <param name="idCartelera">Initial value of the IdCartelera property.</param>
        /// <param name="idPelicula">Initial value of the IdPelicula property.</param>
        /// <param name="idSala">Initial value of the IdSala property.</param>
        /// <param name="fechaHora">Initial value of the FechaHora property.</param>
        public static Cartelera CreateCartelera(global::System.Int32 idCartelera, global::System.Int32 idPelicula, global::System.Int32 idSala, global::System.DateTime fechaHora)
        {
            Cartelera cartelera = new Cartelera();
            cartelera.IdCartelera = idCartelera;
            cartelera.IdPelicula = idPelicula;
            cartelera.IdSala = idSala;
            cartelera.FechaHora = fechaHora;
            return cartelera;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCartelera
        {
            get
            {
                return _IdCartelera;
            }
            set
            {
                if (_IdCartelera != value)
                {
                    OnIdCarteleraChanging(value);
                    ReportPropertyChanging("IdCartelera");
                    _IdCartelera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCartelera");
                    OnIdCarteleraChanged();
                }
            }
        }
        private global::System.Int32 _IdCartelera;
        partial void OnIdCarteleraChanging(global::System.Int32 value);
        partial void OnIdCarteleraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPelicula
        {
            get
            {
                return _IdPelicula;
            }
            set
            {
                OnIdPeliculaChanging(value);
                ReportPropertyChanging("IdPelicula");
                _IdPelicula = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPelicula");
                OnIdPeliculaChanged();
            }
        }
        private global::System.Int32 _IdPelicula;
        partial void OnIdPeliculaChanging(global::System.Int32 value);
        partial void OnIdPeliculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSala
        {
            get
            {
                return _IdSala;
            }
            set
            {
                OnIdSalaChanging(value);
                ReportPropertyChanging("IdSala");
                _IdSala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSala");
                OnIdSalaChanged();
            }
        }
        private global::System.Int32 _IdSala;
        partial void OnIdSalaChanging(global::System.Int32 value);
        partial void OnIdSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHora
        {
            get
            {
                return _FechaHora;
            }
            set
            {
                OnFechaHoraChanging(value);
                ReportPropertyChanging("FechaHora");
                _FechaHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHora");
                OnFechaHoraChanged();
            }
        }
        private global::System.DateTime _FechaHora;
        partial void OnFechaHoraChanging(global::System.DateTime value);
        partial void OnFechaHoraChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Pelicula")]
        public Pelicula Pelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pelicula> PeliculaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Sala", "Sala")]
        public Sala Sala
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sala> SalaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="CategoriaPelicula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoriaPelicula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoriaPelicula object.
        /// </summary>
        /// <param name="idcategoria">Initial value of the idcategoria property.</param>
        public static CategoriaPelicula CreateCategoriaPelicula(global::System.Int32 idcategoria)
        {
            CategoriaPelicula categoriaPelicula = new CategoriaPelicula();
            categoriaPelicula.idcategoria = idcategoria;
            return categoriaPelicula;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcategoria
        {
            get
            {
                return _idcategoria;
            }
            set
            {
                if (_idcategoria != value)
                {
                    OnidcategoriaChanging(value);
                    ReportPropertyChanging("idcategoria");
                    _idcategoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcategoria");
                    OnidcategoriaChanged();
                }
            }
        }
        private global::System.Int32 _idcategoria;
        partial void OnidcategoriaChanging(global::System.Int32 value);
        partial void OnidcategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreCategoria
        {
            get
            {
                return _nombreCategoria;
            }
            set
            {
                OnnombreCategoriaChanging(value);
                ReportPropertyChanging("nombreCategoria");
                _nombreCategoria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreCategoria");
                OnnombreCategoriaChanged();
            }
        }
        private global::System.String _nombreCategoria;
        partial void OnnombreCategoriaChanging(global::System.String value);
        partial void OnnombreCategoriaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_CategoriaPelicula", "Pelicula")]
        public EntityCollection<Pelicula> Pelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "Pelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "Pelicula", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="idcliente">Initial value of the idcliente property.</param>
        /// <param name="direccion">Initial value of the direccion property.</param>
        /// <param name="tipocliente">Initial value of the tipocliente property.</param>
        public static Cliente CreateCliente(global::System.Int32 idcliente, global::System.String direccion, global::System.String tipocliente)
        {
            Cliente cliente = new Cliente();
            cliente.idcliente = idcliente;
            cliente.direccion = direccion;
            cliente.tipocliente = tipocliente;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                if (_idcliente != value)
                {
                    OnidclienteChanging(value);
                    ReportPropertyChanging("idcliente");
                    _idcliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcliente");
                    OnidclienteChanged();
                }
            }
        }
        private global::System.Int32 _idcliente;
        partial void OnidclienteChanging(global::System.Int32 value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidoPaterno
        {
            get
            {
                return _apellidoPaterno;
            }
            set
            {
                OnapellidoPaternoChanging(value);
                ReportPropertyChanging("apellidoPaterno");
                _apellidoPaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidoPaterno");
                OnapellidoPaternoChanged();
            }
        }
        private global::System.String _apellidoPaterno;
        partial void OnapellidoPaternoChanging(global::System.String value);
        partial void OnapellidoPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidoMaterno
        {
            get
            {
                return _apellidoMaterno;
            }
            set
            {
                OnapellidoMaternoChanging(value);
                ReportPropertyChanging("apellidoMaterno");
                _apellidoMaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidoMaterno");
                OnapellidoMaternoChanged();
            }
        }
        private global::System.String _apellidoMaterno;
        partial void OnapellidoMaternoChanging(global::System.String value);
        partial void OnapellidoMaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dni
        {
            get
            {
                return _dni;
            }
            set
            {
                OndniChanging(value);
                ReportPropertyChanging("dni");
                _dni = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dni");
                OndniChanged();
            }
        }
        private Nullable<global::System.Int32> _dni;
        partial void OndniChanging(Nullable<global::System.Int32> value);
        partial void OndniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaNacimiento
        {
            get
            {
                return _fechaNacimiento;
            }
            set
            {
                OnfechaNacimientoChanging(value);
                ReportPropertyChanging("fechaNacimiento");
                _fechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaNacimiento");
                OnfechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaNacimiento;
        partial void OnfechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaNacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipocliente
        {
            get
            {
                return _tipocliente;
            }
            set
            {
                OntipoclienteChanging(value);
                ReportPropertyChanging("tipocliente");
                _tipocliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipocliente");
                OntipoclienteChanged();
            }
        }
        private global::System.String _tipocliente;
        partial void OntipoclienteChanging(global::System.String value);
        partial void OntipoclienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> puntos
        {
            get
            {
                return _puntos;
            }
            set
            {
                OnpuntosChanging(value);
                ReportPropertyChanging("puntos");
                _puntos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("puntos");
                OnpuntosChanged();
            }
        }
        private Nullable<global::System.Int32> _puntos;
        partial void OnpuntosChanging(Nullable<global::System.Int32> value);
        partial void OnpuntosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_PuntajeAcumulado_Cliente", "PuntajeAcumulado")]
        public PuntajeAcumulado PuntajeAcumulado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PuntajeAcumulado>("FideCineModel.FK_PuntajeAcumulado_Cliente", "PuntajeAcumulado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PuntajeAcumulado>("FideCineModel.FK_PuntajeAcumulado_Cliente", "PuntajeAcumulado").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PuntajeAcumulado> PuntajeAcumuladoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PuntajeAcumulado>("FideCineModel.FK_PuntajeAcumulado_Cliente", "PuntajeAcumulado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PuntajeAcumulado>("FideCineModel.FK_PuntajeAcumulado_Cliente", "PuntajeAcumulado", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_TarjetaCliente_Cliente", "TarjetaCliente")]
        public TarjetaCliente TarjetaCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaCliente>("FideCineModel.FK_TarjetaCliente_Cliente", "TarjetaCliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaCliente>("FideCineModel.FK_TarjetaCliente_Cliente", "TarjetaCliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TarjetaCliente> TarjetaClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TarjetaCliente>("FideCineModel.FK_TarjetaCliente_Cliente", "TarjetaCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TarjetaCliente>("FideCineModel.FK_TarjetaCliente_Cliente", "TarjetaCliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_VisitaCliente_Cliente", "VisitaCliente")]
        public EntityCollection<VisitaCliente> VisitaCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VisitaCliente>("FideCineModel.FK_VisitaCliente_Cliente", "VisitaCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VisitaCliente>("FideCineModel.FK_VisitaCliente_Cliente", "VisitaCliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="GeneroPelicula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeneroPelicula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeneroPelicula object.
        /// </summary>
        /// <param name="idgenero">Initial value of the idgenero property.</param>
        public static GeneroPelicula CreateGeneroPelicula(global::System.Int32 idgenero)
        {
            GeneroPelicula generoPelicula = new GeneroPelicula();
            generoPelicula.idgenero = idgenero;
            return generoPelicula;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idgenero
        {
            get
            {
                return _idgenero;
            }
            set
            {
                if (_idgenero != value)
                {
                    OnidgeneroChanging(value);
                    ReportPropertyChanging("idgenero");
                    _idgenero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idgenero");
                    OnidgeneroChanged();
                }
            }
        }
        private global::System.Int32 _idgenero;
        partial void OnidgeneroChanging(global::System.Int32 value);
        partial void OnidgeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreGenero
        {
            get
            {
                return _nombreGenero;
            }
            set
            {
                OnnombreGeneroChanging(value);
                ReportPropertyChanging("nombreGenero");
                _nombreGenero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreGenero");
                OnnombreGeneroChanged();
            }
        }
        private global::System.String _nombreGenero;
        partial void OnnombreGeneroChanging(global::System.String value);
        partial void OnnombreGeneroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_GeneroPelicula", "Pelicula")]
        public EntityCollection<Pelicula> Pelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "Pelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "Pelicula", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Pelicula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pelicula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pelicula object.
        /// </summary>
        /// <param name="idPelicula">Initial value of the IdPelicula property.</param>
        public static Pelicula CreatePelicula(global::System.Int32 idPelicula)
        {
            Pelicula pelicula = new Pelicula();
            pelicula.IdPelicula = idPelicula;
            return pelicula;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPelicula
        {
            get
            {
                return _IdPelicula;
            }
            set
            {
                if (_IdPelicula != value)
                {
                    OnIdPeliculaChanging(value);
                    ReportPropertyChanging("IdPelicula");
                    _IdPelicula = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPelicula");
                    OnIdPeliculaChanged();
                }
            }
        }
        private global::System.Int32 _IdPelicula;
        partial void OnIdPeliculaChanging(global::System.Int32 value);
        partial void OnIdPeliculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idcategoria
        {
            get
            {
                return _idcategoria;
            }
            set
            {
                OnidcategoriaChanging(value);
                ReportPropertyChanging("idcategoria");
                _idcategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcategoria");
                OnidcategoriaChanged();
            }
        }
        private Nullable<global::System.Int32> _idcategoria;
        partial void OnidcategoriaChanging(Nullable<global::System.Int32> value);
        partial void OnidcategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trailer
        {
            get
            {
                return _trailer;
            }
            set
            {
                OntrailerChanging(value);
                ReportPropertyChanging("trailer");
                _trailer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trailer");
                OntrailerChanged();
            }
        }
        private global::System.String _trailer;
        partial void OntrailerChanging(global::System.String value);
        partial void OntrailerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idtipo
        {
            get
            {
                return _idtipo;
            }
            set
            {
                OnidtipoChanging(value);
                ReportPropertyChanging("idtipo");
                _idtipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idtipo");
                OnidtipoChanged();
            }
        }
        private Nullable<global::System.Int32> _idtipo;
        partial void OnidtipoChanging(Nullable<global::System.Int32> value);
        partial void OnidtipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idgenero
        {
            get
            {
                return _idgenero;
            }
            set
            {
                OnidgeneroChanging(value);
                ReportPropertyChanging("idgenero");
                _idgenero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idgenero");
                OnidgeneroChanged();
            }
        }
        private Nullable<global::System.Int32> _idgenero;
        partial void OnidgeneroChanging(Nullable<global::System.Int32> value);
        partial void OnidgeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> duracion
        {
            get
            {
                return _duracion;
            }
            set
            {
                OnduracionChanging(value);
                ReportPropertyChanging("duracion");
                _duracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duracion");
                OnduracionChanged();
            }
        }
        private Nullable<global::System.Int32> _duracion;
        partial void OnduracionChanging(Nullable<global::System.Int32> value);
        partial void OnduracionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Cartelera")]
        public EntityCollection<Cartelera> Cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Pelicula", "Cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Pelicula", "Cartelera", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_CategoriaPelicula", "CategoriaPelicula")]
        public CategoriaPelicula CategoriaPelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaPelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "CategoriaPelicula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaPelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "CategoriaPelicula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CategoriaPelicula> CategoriaPeliculaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CategoriaPelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "CategoriaPelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CategoriaPelicula>("FideCineModel.FK_Pelicula_CategoriaPelicula", "CategoriaPelicula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_GeneroPelicula", "GeneroPelicula")]
        public GeneroPelicula GeneroPelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneroPelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "GeneroPelicula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneroPelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "GeneroPelicula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GeneroPelicula> GeneroPeliculaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneroPelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "GeneroPelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GeneroPelicula>("FideCineModel.FK_Pelicula_GeneroPelicula", "GeneroPelicula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_TipoPelicula", "TipoPelicula")]
        public TipoPelicula TipoPelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoPelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "TipoPelicula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoPelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "TipoPelicula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoPelicula> TipoPeliculaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoPelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "TipoPelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoPelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "TipoPelicula", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Producto object.
        /// </summary>
        /// <param name="idProducto">Initial value of the IdProducto property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Producto CreateProducto(global::System.Int32 idProducto, global::System.String nombre, global::System.String estado)
        {
            Producto producto = new Producto();
            producto.IdProducto = idProducto;
            producto.Nombre = nombre;
            producto.Estado = estado;
            return producto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProducto
        {
            get
            {
                return _IdProducto;
            }
            set
            {
                if (_IdProducto != value)
                {
                    OnIdProductoChanging(value);
                    ReportPropertyChanging("IdProducto");
                    _IdProducto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProducto");
                    OnIdProductoChanged();
                }
            }
        }
        private global::System.Int32 _IdProducto;
        partial void OnIdProductoChanging(global::System.Int32 value);
        partial void OnIdProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Promocion_Producto", "Promocion")]
        public EntityCollection<Promocion> Promocion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Promocion>("FideCineModel.FK_Promocion_Producto", "Promocion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Promocion>("FideCineModel.FK_Promocion_Producto", "Promocion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Promocion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promocion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Promocion object.
        /// </summary>
        /// <param name="idPromocion">Initial value of the IdPromocion property.</param>
        /// <param name="puntos">Initial value of the Puntos property.</param>
        /// <param name="vigenciaInicio">Initial value of the vigenciaInicio property.</param>
        /// <param name="vigenciaFin">Initial value of the vigenciaFin property.</param>
        /// <param name="idProducto">Initial value of the IdProducto property.</param>
        public static Promocion CreatePromocion(global::System.Int32 idPromocion, global::System.Int32 puntos, global::System.DateTime vigenciaInicio, global::System.DateTime vigenciaFin, global::System.Int32 idProducto)
        {
            Promocion promocion = new Promocion();
            promocion.IdPromocion = idPromocion;
            promocion.Puntos = puntos;
            promocion.vigenciaInicio = vigenciaInicio;
            promocion.vigenciaFin = vigenciaFin;
            promocion.IdProducto = idProducto;
            return promocion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPromocion
        {
            get
            {
                return _IdPromocion;
            }
            set
            {
                if (_IdPromocion != value)
                {
                    OnIdPromocionChanging(value);
                    ReportPropertyChanging("IdPromocion");
                    _IdPromocion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPromocion");
                    OnIdPromocionChanged();
                }
            }
        }
        private global::System.Int32 _IdPromocion;
        partial void OnIdPromocionChanging(global::System.Int32 value);
        partial void OnIdPromocionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puntos
        {
            get
            {
                return _Puntos;
            }
            set
            {
                OnPuntosChanging(value);
                ReportPropertyChanging("Puntos");
                _Puntos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Puntos");
                OnPuntosChanged();
            }
        }
        private global::System.Int32 _Puntos;
        partial void OnPuntosChanging(global::System.Int32 value);
        partial void OnPuntosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime vigenciaInicio
        {
            get
            {
                return _vigenciaInicio;
            }
            set
            {
                OnvigenciaInicioChanging(value);
                ReportPropertyChanging("vigenciaInicio");
                _vigenciaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vigenciaInicio");
                OnvigenciaInicioChanged();
            }
        }
        private global::System.DateTime _vigenciaInicio;
        partial void OnvigenciaInicioChanging(global::System.DateTime value);
        partial void OnvigenciaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime vigenciaFin
        {
            get
            {
                return _vigenciaFin;
            }
            set
            {
                OnvigenciaFinChanging(value);
                ReportPropertyChanging("vigenciaFin");
                _vigenciaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vigenciaFin");
                OnvigenciaFinChanged();
            }
        }
        private global::System.DateTime _vigenciaFin;
        partial void OnvigenciaFinChanging(global::System.DateTime value);
        partial void OnvigenciaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProducto
        {
            get
            {
                return _IdProducto;
            }
            set
            {
                OnIdProductoChanging(value);
                ReportPropertyChanging("IdProducto");
                _IdProducto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProducto");
                OnIdProductoChanged();
            }
        }
        private global::System.Int32 _IdProducto;
        partial void OnIdProductoChanging(global::System.Int32 value);
        partial void OnIdProductoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Promocion_Producto", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("FideCineModel.FK_Promocion_Producto", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("FideCineModel.FK_Promocion_Producto", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("FideCineModel.FK_Promocion_Producto", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("FideCineModel.FK_Promocion_Producto", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="PuntajeAcumulado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PuntajeAcumulado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PuntajeAcumulado object.
        /// </summary>
        /// <param name="idcliente">Initial value of the idcliente property.</param>
        /// <param name="puntos">Initial value of the Puntos property.</param>
        public static PuntajeAcumulado CreatePuntajeAcumulado(global::System.Int32 idcliente, global::System.Int32 puntos)
        {
            PuntajeAcumulado puntajeAcumulado = new PuntajeAcumulado();
            puntajeAcumulado.idcliente = idcliente;
            puntajeAcumulado.Puntos = puntos;
            return puntajeAcumulado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                if (_idcliente != value)
                {
                    OnidclienteChanging(value);
                    ReportPropertyChanging("idcliente");
                    _idcliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcliente");
                    OnidclienteChanged();
                }
            }
        }
        private global::System.Int32 _idcliente;
        partial void OnidclienteChanging(global::System.Int32 value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puntos
        {
            get
            {
                return _Puntos;
            }
            set
            {
                OnPuntosChanging(value);
                ReportPropertyChanging("Puntos");
                _Puntos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Puntos");
                OnPuntosChanged();
            }
        }
        private global::System.Int32 _Puntos;
        partial void OnPuntosChanging(global::System.Int32 value);
        partial void OnPuntosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_PuntajeAcumulado_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_PuntajeAcumulado_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_PuntajeAcumulado_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_PuntajeAcumulado_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("FideCineModel.FK_PuntajeAcumulado_Cliente", "Cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Sala")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sala : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sala object.
        /// </summary>
        /// <param name="idSala">Initial value of the IdSala property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Sala CreateSala(global::System.Int32 idSala, global::System.String nombre, global::System.String estado)
        {
            Sala sala = new Sala();
            sala.IdSala = idSala;
            sala.Nombre = nombre;
            sala.Estado = estado;
            return sala;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSala
        {
            get
            {
                return _IdSala;
            }
            set
            {
                if (_IdSala != value)
                {
                    OnIdSalaChanging(value);
                    ReportPropertyChanging("IdSala");
                    _IdSala = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdSala");
                    OnIdSalaChanged();
                }
            }
        }
        private global::System.Int32 _IdSala;
        partial void OnIdSalaChanging(global::System.Int32 value);
        partial void OnIdSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Sala", "Cartelera")]
        public EntityCollection<Cartelera> Cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Sala", "Cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Sala", "Cartelera", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="TarjetaCliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TarjetaCliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TarjetaCliente object.
        /// </summary>
        /// <param name="idcliente">Initial value of the idcliente property.</param>
        public static TarjetaCliente CreateTarjetaCliente(global::System.Int32 idcliente)
        {
            TarjetaCliente tarjetaCliente = new TarjetaCliente();
            tarjetaCliente.idcliente = idcliente;
            return tarjetaCliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                if (_idcliente != value)
                {
                    OnidclienteChanging(value);
                    ReportPropertyChanging("idcliente");
                    _idcliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcliente");
                    OnidclienteChanged();
                }
            }
        }
        private global::System.Int32 _idcliente;
        partial void OnidclienteChanging(global::System.Int32 value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipotarjeta
        {
            get
            {
                return _tipotarjeta;
            }
            set
            {
                OntipotarjetaChanging(value);
                ReportPropertyChanging("tipotarjeta");
                _tipotarjeta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipotarjeta");
                OntipotarjetaChanged();
            }
        }
        private global::System.String _tipotarjeta;
        partial void OntipotarjetaChanging(global::System.String value);
        partial void OntipotarjetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> puntos
        {
            get
            {
                return _puntos;
            }
            set
            {
                OnpuntosChanging(value);
                ReportPropertyChanging("puntos");
                _puntos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("puntos");
                OnpuntosChanged();
            }
        }
        private Nullable<global::System.Int32> _puntos;
        partial void OnpuntosChanging(Nullable<global::System.Int32> value);
        partial void OnpuntosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_TarjetaCliente_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_TarjetaCliente_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_TarjetaCliente_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_TarjetaCliente_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("FideCineModel.FK_TarjetaCliente_Cliente", "Cliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="TipoPelicula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoPelicula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoPelicula object.
        /// </summary>
        /// <param name="idtipo">Initial value of the idtipo property.</param>
        public static TipoPelicula CreateTipoPelicula(global::System.Int32 idtipo)
        {
            TipoPelicula tipoPelicula = new TipoPelicula();
            tipoPelicula.idtipo = idtipo;
            return tipoPelicula;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtipo
        {
            get
            {
                return _idtipo;
            }
            set
            {
                if (_idtipo != value)
                {
                    OnidtipoChanging(value);
                    ReportPropertyChanging("idtipo");
                    _idtipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idtipo");
                    OnidtipoChanged();
                }
            }
        }
        private global::System.Int32 _idtipo;
        partial void OnidtipoChanging(global::System.Int32 value);
        partial void OnidtipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreTipo
        {
            get
            {
                return _nombreTipo;
            }
            set
            {
                OnnombreTipoChanging(value);
                ReportPropertyChanging("nombreTipo");
                _nombreTipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreTipo");
                OnnombreTipoChanged();
            }
        }
        private global::System.String _nombreTipo;
        partial void OnnombreTipoChanging(global::System.String value);
        partial void OnnombreTipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Pelicula_TipoPelicula", "Pelicula")]
        public EntityCollection<Pelicula> Pelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "Pelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pelicula>("FideCineModel.FK_Pelicula_TipoPelicula", "Pelicula", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="VisitaCliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VisitaCliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisitaCliente object.
        /// </summary>
        /// <param name="idVisitaCliente">Initial value of the IdVisitaCliente property.</param>
        public static VisitaCliente CreateVisitaCliente(global::System.Int32 idVisitaCliente)
        {
            VisitaCliente visitaCliente = new VisitaCliente();
            visitaCliente.IdVisitaCliente = idVisitaCliente;
            return visitaCliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVisitaCliente
        {
            get
            {
                return _IdVisitaCliente;
            }
            set
            {
                if (_IdVisitaCliente != value)
                {
                    OnIdVisitaClienteChanging(value);
                    ReportPropertyChanging("IdVisitaCliente");
                    _IdVisitaCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVisitaCliente");
                    OnIdVisitaClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdVisitaCliente;
        partial void OnIdVisitaClienteChanging(global::System.Int32 value);
        partial void OnIdVisitaClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdCartelera
        {
            get
            {
                return _IdCartelera;
            }
            set
            {
                OnIdCarteleraChanging(value);
                ReportPropertyChanging("IdCartelera");
                _IdCartelera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCartelera");
                OnIdCarteleraChanged();
            }
        }
        private Nullable<global::System.Int32> _IdCartelera;
        partial void OnIdCarteleraChanging(Nullable<global::System.Int32> value);
        partial void OnIdCarteleraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idcliente
        {
            get
            {
                return _idcliente;
            }
            set
            {
                OnidclienteChanging(value);
                ReportPropertyChanging("idcliente");
                _idcliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcliente");
                OnidclienteChanged();
            }
        }
        private Nullable<global::System.Int32> _idcliente;
        partial void OnidclienteChanging(Nullable<global::System.Int32> value);
        partial void OnidclienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CantidadEntradas
        {
            get
            {
                return _CantidadEntradas;
            }
            set
            {
                OnCantidadEntradasChanging(value);
                ReportPropertyChanging("CantidadEntradas");
                _CantidadEntradas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadEntradas");
                OnCantidadEntradasChanged();
            }
        }
        private Nullable<global::System.Int32> _CantidadEntradas;
        partial void OnCantidadEntradasChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadEntradasChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_VisitaCliente_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_VisitaCliente_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_VisitaCliente_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("FideCineModel.FK_VisitaCliente_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("FideCineModel.FK_VisitaCliente_Cliente", "Cliente", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
