//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDECINEWeb.SalaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaServiceReference.ISalaService")]
    public interface ISalaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaService/listar", ReplyAction="http://tempuri.org/ISalaService/listarResponse")]
        FIDECINEService.Dominio.SalaBE[] listar(string str_pNombre, string str_pEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaServiceChannel : FIDECINEWeb.SalaServiceReference.ISalaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaServiceClient : System.ServiceModel.ClientBase<FIDECINEWeb.SalaServiceReference.ISalaService>, FIDECINEWeb.SalaServiceReference.ISalaService {
        
        public SalaServiceClient() {
        }
        
        public SalaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FIDECINEService.Dominio.SalaBE[] listar(string str_pNombre, string str_pEstado) {
            return base.Channel.listar(str_pNombre, str_pEstado);
        }
    }
}
