//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Pelicula", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Pelicula), "Cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Cartelera), true)]
[assembly: EdmRelationshipAttribute("FideCineModel", "FK_Cartelera_Sala", "Sala", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FIDECINEService.Sala), "Cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FIDECINEService.Cartelera), true)]

#endregion

namespace FIDECINEService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FideCineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FideCineEntities object using the connection string found in the 'FideCineEntities' section of the application configuration file.
        /// </summary>
        public FideCineEntities() : base("name=FideCineEntities", "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FideCineEntities object.
        /// </summary>
        public FideCineEntities(string connectionString) : base(connectionString, "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FideCineEntities object.
        /// </summary>
        public FideCineEntities(EntityConnection connection) : base(connection, "FideCineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cartelera> Cartelera
        {
            get
            {
                if ((_Cartelera == null))
                {
                    _Cartelera = base.CreateObjectSet<Cartelera>("Cartelera");
                }
                return _Cartelera;
            }
        }
        private ObjectSet<Cartelera> _Cartelera;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pelicula> Pelicula
        {
            get
            {
                if ((_Pelicula == null))
                {
                    _Pelicula = base.CreateObjectSet<Pelicula>("Pelicula");
                }
                return _Pelicula;
            }
        }
        private ObjectSet<Pelicula> _Pelicula;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sala> Sala
        {
            get
            {
                if ((_Sala == null))
                {
                    _Sala = base.CreateObjectSet<Sala>("Sala");
                }
                return _Sala;
            }
        }
        private ObjectSet<Sala> _Sala;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cartelera EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCartelera(Cartelera cartelera)
        {
            base.AddObject("Cartelera", cartelera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pelicula EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPelicula(Pelicula pelicula)
        {
            base.AddObject("Pelicula", pelicula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sala EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSala(Sala sala)
        {
            base.AddObject("Sala", sala);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Cartelera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cartelera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cartelera object.
        /// </summary>
        /// <param name="idCartelera">Initial value of the IdCartelera property.</param>
        /// <param name="idPelicula">Initial value of the IdPelicula property.</param>
        /// <param name="idSala">Initial value of the IdSala property.</param>
        /// <param name="fechaHora">Initial value of the FechaHora property.</param>
        public static Cartelera CreateCartelera(global::System.Int32 idCartelera, global::System.Int32 idPelicula, global::System.Int32 idSala, global::System.DateTime fechaHora)
        {
            Cartelera cartelera = new Cartelera();
            cartelera.IdCartelera = idCartelera;
            cartelera.IdPelicula = idPelicula;
            cartelera.IdSala = idSala;
            cartelera.FechaHora = fechaHora;
            return cartelera;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCartelera
        {
            get
            {
                return _IdCartelera;
            }
            set
            {
                if (_IdCartelera != value)
                {
                    OnIdCarteleraChanging(value);
                    ReportPropertyChanging("IdCartelera");
                    _IdCartelera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCartelera");
                    OnIdCarteleraChanged();
                }
            }
        }
        private global::System.Int32 _IdCartelera;
        partial void OnIdCarteleraChanging(global::System.Int32 value);
        partial void OnIdCarteleraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPelicula
        {
            get
            {
                return _IdPelicula;
            }
            set
            {
                OnIdPeliculaChanging(value);
                ReportPropertyChanging("IdPelicula");
                _IdPelicula = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPelicula");
                OnIdPeliculaChanged();
            }
        }
        private global::System.Int32 _IdPelicula;
        partial void OnIdPeliculaChanging(global::System.Int32 value);
        partial void OnIdPeliculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSala
        {
            get
            {
                return _IdSala;
            }
            set
            {
                OnIdSalaChanging(value);
                ReportPropertyChanging("IdSala");
                _IdSala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSala");
                OnIdSalaChanged();
            }
        }
        private global::System.Int32 _IdSala;
        partial void OnIdSalaChanging(global::System.Int32 value);
        partial void OnIdSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHora
        {
            get
            {
                return _FechaHora;
            }
            set
            {
                OnFechaHoraChanging(value);
                ReportPropertyChanging("FechaHora");
                _FechaHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHora");
                OnFechaHoraChanged();
            }
        }
        private global::System.DateTime _FechaHora;
        partial void OnFechaHoraChanging(global::System.DateTime value);
        partial void OnFechaHoraChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Pelicula")]
        public Pelicula Pelicula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pelicula> PeliculaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pelicula>("FideCineModel.FK_Cartelera_Pelicula", "Pelicula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Sala", "Sala")]
        public Sala Sala
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sala> SalaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sala>("FideCineModel.FK_Cartelera_Sala", "Sala", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Pelicula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pelicula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pelicula object.
        /// </summary>
        /// <param name="idPelicula">Initial value of the IdPelicula property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Pelicula CreatePelicula(global::System.Int32 idPelicula, global::System.String nombre, global::System.String estado)
        {
            Pelicula pelicula = new Pelicula();
            pelicula.IdPelicula = idPelicula;
            pelicula.Nombre = nombre;
            pelicula.Estado = estado;
            return pelicula;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPelicula
        {
            get
            {
                return _IdPelicula;
            }
            set
            {
                if (_IdPelicula != value)
                {
                    OnIdPeliculaChanging(value);
                    ReportPropertyChanging("IdPelicula");
                    _IdPelicula = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPelicula");
                    OnIdPeliculaChanged();
                }
            }
        }
        private global::System.Int32 _IdPelicula;
        partial void OnIdPeliculaChanging(global::System.Int32 value);
        partial void OnIdPeliculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Pelicula", "Cartelera")]
        public EntityCollection<Cartelera> Cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Pelicula", "Cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Pelicula", "Cartelera", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FideCineModel", Name="Sala")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sala : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sala object.
        /// </summary>
        /// <param name="idSala">Initial value of the IdSala property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Sala CreateSala(global::System.Int32 idSala, global::System.String nombre, global::System.String estado)
        {
            Sala sala = new Sala();
            sala.IdSala = idSala;
            sala.Nombre = nombre;
            sala.Estado = estado;
            return sala;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSala
        {
            get
            {
                return _IdSala;
            }
            set
            {
                if (_IdSala != value)
                {
                    OnIdSalaChanging(value);
                    ReportPropertyChanging("IdSala");
                    _IdSala = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdSala");
                    OnIdSalaChanged();
                }
            }
        }
        private global::System.Int32 _IdSala;
        partial void OnIdSalaChanging(global::System.Int32 value);
        partial void OnIdSalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FideCineModel", "FK_Cartelera_Sala", "Cartelera")]
        public EntityCollection<Cartelera> Cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Sala", "Cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cartelera>("FideCineModel.FK_Cartelera_Sala", "Cartelera", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
